global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'telegram'

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token_file: '/etc/alertmanager/telegram_token'
    chat_id: 8584821168
    api_url: 'https://api.telegram.org'
    send_resolved: true
    parse_mode: 'HTML'
    message: |
      {{ range .Alerts -}}
      {{ if eq .Status "firing" -}}
      {{ if eq .Labels.severity "critical" }}🚨{{ else if eq .Labels.severity "warning" }}⚠️{{ else }}ℹ️{{ end }} <b>{{ .Labels.alertname }}</b> on <b>{{ or .Labels.address "Device" }}</b>
      {{- if .Annotations.description }}
      {{ .Annotations.description }}
      {{- end }}
      {{- else -}}
      ✅ <b>RESOLVED</b> - <b>{{ .Labels.alertname }}</b> on <b>{{ or .Labels.address "Device" }}</b>
      {{- end }}
      {{ end }}
