global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'telegram'

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token_file: '/etc/alertmanager/telegram_token'
    chat_id: 8584821168
    api_url: 'https://api.telegram.org'
    send_resolved: true
    parse_mode: 'HTML'
    message: |
      <b>{{ if eq .Status "firing" }}🔔 NOTIFICATION{{ else }}✅ RESOLVED{{ end }}</b>
      {{ range .Alerts }}
      {{ if eq .Status "firing" -}}
      {{ if eq .Labels.severity "critical" }}🚨 <b>[CRITICAL]</b> {{ else if eq .Labels.severity "warning" }}⚠️ <b>[WARNING]</b> {{ else }}ℹ️ <b>[INFO]</b> {{ end -}}
      {{- else -}}
      ✅ [RESOLVED] {{ end -}}
      <b>{{ .Annotations.summary }}</b>
      {{ .Annotations.description }}
      {{ end }}
