services:
  mosquitto:
    image: eclipse-mosquitto:2.1-alpine
    container_name: mosquitto-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: unless-stopped
