[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = ""
  omit_hostname = true

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "sensors/bme280",
  ]
  data_format = "json"
  tag_keys = ["address", "mac"]

[[outputs.influxdb]]
  urls = ["http://victoriametrics:8428"]
  database = "sensors"
  skip_database_creation = true

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "$SYS/broker/clients/connected",
    "$SYS/broker/clients/total",
  ]
  data_format = "value"
  data_type = "integer"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "$SYS/broker/uptime",
  ]
  data_format = "value"
  data_type = "string"

[[inputs.cpu]]
  percpu = false
  totalcpu = true
  collect_cpu_time = false
  report_active = false
  interval = "1m"

[[inputs.mem]]
  interval = "1m"

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
  interval = "5m"

