# Enable I2C
CONFIG_I2C=y
CONFIG_GPIO=y

# Enable Sensor subsystem
CONFIG_SENSOR=y

# Enable WiFi
CONFIG_WIFI=y
CONFIG_CYW43439=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_NET_DHCPV4=y

# Networking
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_UDP=y

# MQTT
CONFIG_MQTT_LIB=y

# JSON
CONFIG_JSON_LIBRARY=y

# Logging
CONFIG_LOG=y
CONFIG_NET_LOG=y
CONFIG_WIFI_LOG_LEVEL_DBG=y
CONFIG_NET_L2_WIFI_MGMT_LOG_LEVEL_DBG=y

# Networking Sockets
CONFIG_NET_SOCKETS=y
CONFIG_POSIX_API=y
CONFIG_TEST_RANDOM_GENERATOR=y

# WiFi Config (Kconfig mapped) - set actual credentials in local.conf (ignored by Git)
CONFIG_APP_WIFI_SSID="your-ssid-here"
CONFIG_APP_WIFI_PASSWORD="your-password-here"
CONFIG_APP_MQTT_BROKER_HOST="192.168.1.39"
CONFIG_APP_MQTT_BROKER_PORT=8883
CONFIG_APP_MQTT_TOPIC="sensors/bme280"
CONFIG_APP_MQTT_USERNAME="device_user"
CONFIG_APP_MQTT_PASSWORD="device_pass"

# TLS Configuration
CONFIG_MQTT_LIB_TLS=y
CONFIG_NET_SOCKETS_SOCKOPT_TLS=y
CONFIG_TLS_CREDENTIALS=y
CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_BUILTIN=y
CONFIG_MBEDTLS_CIPHERSUITE_TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256=y
CONFIG_MBEDTLS_PEM_PARSE_C=y

# Cut TLS record buffer 16KB → 4KB (saves ~24KB heap)
CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN=4096


# Application specific settings
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_HEAP_MEM_POOL_SIZE=65536

# C++ Support
CONFIG_CPP=y
CONFIG_STD_CPP20=y
CONFIG_REQUIRES_FULL_LIBCPP=y

# Floating point and JSON library FP support
CONFIG_JSON_LIBRARY_FP_SUPPORT=y

